name: codecov.io

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov
          pip install pytest-mock
          python setup.py install

      - name: Run tests and collect coverage
        run: |
          export PACKAGE_LOCATION=`python -c "import sys; sys.path.pop(0); import academic_tracker; print(academic_tracker.__path__[0])"`
          echo "$PACKAGE_LOCATION"
          pytest --cov=$PACKAGE_LOCATION --cov-report=xml -s

      # codecov
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2